spring:
  application:
    name: spring-data-jpa-demo
  # Jpa配置
  jpa: 
    generate-ddl: true
    hibernate: 
      ddl-auto: create-drop
    show-sql: true
  # mysql数据库访问配置
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true
#    username: root
#    password: root
  # log4jdbc数据库访问配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    
  # redis 配置
  redis:
    database: 0 
    host: 127.0.0.1
    port: 6379
    password: 
    pool.max-active: 8
    pool.max-wait: -1
    pool.max-idle: 8
    pool.min-idle: 0
    timeout: 0
  output: 
    ansi: 
      enabled: DETECT

server: 
  port: 8080


# logging
logging:
  config: classpath:logback-boot.xml
  level:
    root: info
    com: 
      licerlee: debug
